services:
  military_district:
    image: postgres:17
    environment:
      POSTGRES_DB: military_district
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: