CREATE TABLE IF NOT EXISTS combat_equipments
(
    id SERIAL PRIMARY KEY,
    serial_number VARCHAR(255) NOT NULL UNIQUE,
    type_id INTEGER REFERENCES combat_equipment_types(id) ON DELETE CASCADE ON UPDATE CASCADE,
    unit_name VARCHAR(255) REFERENCES units(name) ON DELETE SET NULL ON UPDATE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
