spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/military_district
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8080