name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Zulu OpenJDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Start services with Docker Compose
        run: docker compose -f docker-compose.dev.yml up -d

      - name: Wait for Database
        run: |
          until docker compose -f docker-compose.dev.yml exec military_district pg_isready -U postgres; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Build with Gradle
        run: ./gradlew bootJar --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Run coverage tests
        if: github.ref == 'refs/heads/main'
        run: ./gradlew jacocoTestReport

      - name: Upload test coverage report
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./build/reports/jacoco/test/html

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v
